/**
 * Middleware for catching errors thrown in routes
 * @param ctx
 * @returns {function}
 */
export default async function(ctx, next) {
  try {
    await next()
  } catch(error) {
    // Exceptions are generated by our app (ex: Wrong login)
    // So we don't need to log the whole stacktrace
    if (error.constructor.name === 'Exception') {
      console.error(error.message)
      return ctx.throw(400, error.message)
    }

    console.error(error)
    return ctx.throw(400, error.toString())
  }
}
